### ISSUE TITLE
New-ACMEOrder - would like an option to set a key size

### ISSUE THREAD

**Issue by BlackV** [PKISharp/ACMESharpCore-PowerShell#21]
for example
New-ACMEOrder $state -Identifiers $identifier -CertKeyLength 4096

Looks like currently it defaults to 4096 which is plenty large

**Comment by glatzert** [comment]
The ACME Protocol does not set a key length during the creation of an order. The order describes which identifiers (~DNS names) you want to have in your certificate. And for which you need to fulfill the challenges.

After you completed the challenges, it's up to you to create a certificate key.
You do this with `New-ACMECertificateKey -Path "$stateDir\$dnsName.key.xml";` (see sample from the readme.md of this repository). The command will have a key size of 2048. While the key size is meant to be settable, currently the Cmdlet will only allow 2048 for the KeySize parameter, since LE will not allow any other size.

The cmdlets all come with documentation, so get-help will show you all parameters for all commands with a short explanation, but feel free to open issues, if something is not clear about the cmdlets.

**Comment by ebekker** [comment]
According to [this](https://community.letsencrypt.org/t/is-it-possible/15132/3) it looks like the supported RSA key sizes by Let's Encrypt are 2048, 3072, and 4096.
