### ISSUE TITLE
Status never change from Invalid - Help needed

### ISSUE THREAD

**Issue by ThorkilG12** [PKISharp/ACMESharpCore-PowerShell#40]
Hi
I can not figure out what is wrong here... I think I have attached all relevant info.
Hope you can help

[AcmeState.zip](https://github.com/PKISharp/ACMESharpCore-PowerShell/files/3722191/AcmeState.zip)
[ps_log.txt](https://github.com/PKISharp/ACMESharpCore-PowerShell/files/3722193/ps_log.txt)
[.well-known.zip](https://github.com/PKISharp/ACMESharpCore-PowerShell/files/3722194/default.well-known.zip)

[My_Acme_v2.zip](https://github.com/PKISharp/ACMESharpCore-PowerShell/files/3722195/My_Acme_v2.zip)

Regards from rainy Copenhagen  :-)

**Comment by glatzert** [comment]
Hi to Copenhagen,
essentially „invalid“ means, ACME tried to get read your challenge, but was not able to and thus declared the order to be invalid (afaik that state won’t recover unless you create a new order).
I threw the absolute URL of the in my browser and got a 403 (Forbidden). The URL needs to be available from the internet or the process will fail.

Just for awareness: Your account-key is now “public”, but you’re in staging currently, so that seems acceptable.

Best regards from Mainz

**Comment by ThorkilG12** [comment]
Thanks... I was a fault in my Apache Setup. Thanks to you I got to the next step. Now I have a PFX file.
I have use a lot of time automating ACMEv1 in powershell to generate three files per domain.
How do I get the three files I need ? 
ca_bundle.crt - IssuerSerialNumber
private.key - KeyPemFile
certificate.crt - CrtPemFile

What should I do to get over the 'Your account-key is now “public”' issue...
Is this a key that is in use for all my domains ?
Thanks in advance....

**Comment by glatzert** [comment]
If you used the recipe from the readme file, you can probably just ditch the account (or the account key), cause it’s registered with staging only. Nevertheless the ACME-State directory contains your account key, which you want to keep secret, since it identifies you.

Splitting the files is currently not supported by the module, but you can use openssl for that.

**Comment by ThorkilG12** [comment]
It seams that the pfx file is protected by some password.?

In my acmeV1 there was No password...



Venlig hilsen
Thorkil Johansen
+45 4070 6547

man. 14. okt. 2019 17.01 skrev Thomas Glatzer <notifications@github.com>:

**Comment by glatzert** [comment]
You probably used Export-ACMECertificate with a password?

**Comment by ThorkilG12** [comment]
Hi again
I'm following your readme the best I can:
Export-ACMECertificate $state -Order $order -CertificateKey $certKey -Path
"$stateDir\$dnsName.pfx";
[image: image.png]

I know that you guys is properly the best one can get for the Acme protocol.
But try to put yourself in my position.
Suddenly the AcmeV1 stop working, and I have the risk that my certificates
run out.

Notice that I don't have the time to become an Acme expert... what I see is
me loosing valuable time trying to get the AcmeV2 to run, and the forget
all about it.

I don't know if it is LetsEncrypt that has forced this problem upon me, but
for sure it gives a lot of frustration.
Can I book an hour with you or ebekker or how can I get an automated
powershell to take care of my certificates ?
*Br*
*Thorkil Johansen*
*Tel: +45 4070 6547*



Den man. 14. okt. 2019 kl. 20.21 skrev Thomas Glatzer <
notifications@github.com>:
