### ISSUE TITLE
Random failures and erroractionpreference causing other scripts to fail

### ISSUE THREAD

**Issue by feueru** [PKISharp/ACMESharpCore-PowerShell#47]
When trying to use the acme-ps module in another script to automate renewals it seems to randomly fail for me when Invoke-SignedWebRequest is called. Simply retrying the command tends to get past the error, however on line 1183 the throw can end the script due to the default erroractionpreferece. Simply adding $errroractionpreference = "continue" to acme-ps.psm1 seems to resolve this ending my script (for whatever reason if I add this to the script calling acme-ps it does not work).

1. Am I thick and is there a better workaround than this?
2. what are the possibilities of adding this to the main branch? drawbacks?

Edit: changing the throw to a write-error would probably be better, Q1 answered: yes I am

**Comment by glatzert** [comment]
Could you take a look into the error details?
Essentially the `IsError` should only be true for HttpStatus Codes (returned from Let's Encrypt) > 400. Which normally means something went wrong, and we've no way to recover or do something useful afterwards.
That's why it issues an terminating error.

If you want to just try again, you can catch it with try {} catch {}.

Changing the throw to write-error, would not terminate the currently running function and would end up in more errors being thrown.

**Comment by feueru** [comment]
Error:
`Server returned problem (Status: 400).
@{type=urn:ietf:params:acme:error:badNonce; detail=JWS has an invalid anti-replay nonce:
"0102awhAU9D2anavAc27bLVzM5Sfl-OIS0kk2BFWkl_Atfk"; status=400}
At C:\Program Files\WindowsPowerShell\Modules\acme-ps\1.1.2\ACME-PS.psm1:1183 char:13
+             throw "$($response.ErrorMessage)`n$($response.Content)";
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Server returned...k"; status=400}:String) [], RuntimeException
    + FullyQualifiedErrorId : Server returned problem (Status: 400).
    @{type=urn:ietf:params:acme:error:badNonce; detail=JWS has an invalid anti-replay nonce: "0102awhAU9D2anavAc27bLVz
   M5Sfl-OIS0kk2BFWkl_Atfk"; status=400}`

if i try it again a few times with the same state and nonce it eventually goes through fine.

my thoughts on using a throw instead of write-error is that a throw docent seem to respect erroractionpreferences set by a script calling the module where a write-error would. i.e. It'd be better to give the user the decision on how to handle errors rather than deciding for them.

**Comment by glatzert** [comment]
Ah sorry, I was talking nonsense before.
The Response will report an error for everything HttpStatus >= 400.
Furthermore it'll extract a given nonce, if any and set that to the status, so it's kind of self-healing.
Essentially (if you do not some kind of multi-session or multi-threading) the nonce should be okay with the next call.

The throw is used, because the functions normally won't end with calling Let's Encrypt, but will also use the result - that might be "lazy" on my side, because I did not want to use -errorAction 'Stop' everywhere. Also - your script probably cannot go on if such an error occures as well.

To relieve the problem, it'd be possible to use the problem-type (urn:ietf:params:acme:error:badNonce) to detect a faulty nonce and automatically retry with a new one. The detection could be done in `AcmeHttpResponse` and `Invoke-SignedWebRequest` could manage (a single) retry.

**Comment by glatzert** [comment]
I included an automatic retry on nonce error.
Also you can now get the error details from the thrown exception.
Will be available in 1.1.3 once it's in the gallery. If you like to get a head start, try the beta ;).
